version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 12345
      ACCEPT_EULA: Y
    ports:
      - 1433:1433

  authapi:
    image: authapi
    build:
      context: .
      dockerfile: Microservices/AuthMicroservice/AuthAPI/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - sqlserver
      - redis_users 

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: financial_accounts_db
    ports:
      - 5432:5432

  accountspresentation:
    image: accountspresentation
    build:
      context: .
      dockerfile: Microservices/AccountsMicroservice/AccountsPL/Dockerfile
    ports:
      - 8002:80
    depends_on:
      - postgresql
      - redis_accounts

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  operationsapi:
    image: operationsapi
    build:
      context: .
      dockerfile: Microservices/OperationsMicroservice/OperationsAPI/Dockerfile
    ports:
      - 8003:80
    depends_on:
      - mongodb
      - redis_operations

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672

  redis_accounts:
    image: redis
    ports:
      - "6379:6379"
  redis_operations:
    image: redis
    ports:
      - "6380:6379"
  redis_users:
    image: redis
    ports:
      - "6390:6379"
      
  ocelotapigateway:
    image: ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateway/OcelotAPIGateway/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - accountspresentation
      - authapi
      - operationsapi
