global using Auth.Application.Interfaces;
global using Auth.Application.Models;
global using Auth.Application.Producers;
global using Auth.Application.Services;
global using Auth.Core.Entities;
global using AutoMapper;
global using Microsoft.AspNetCore.Identity;
global using Moq;
global using Xunit;